name: Build and deploy to GitHub Pages

on:
  push:
    branches:
      - main   # change if apnar default branch onno

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'   # change if apnar node version onno

      - name: Install dependencies
        run: npm ci

      - name: Build (static export)
        run: npm run build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          publish_branch: gh-pages
